id: ICFFADD88
legacy_id: P006668
ocr_import_info:
  bdrc_scan_id: W1KG22301
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T21:27:00'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T13:07:39.608538+00:00'
last_modified: 2022-08-31 21:08:24.754803
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG22301
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG22301
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྐྱེས་རབས་བརྒྱ་པ།
  author: ཀརྨ་པ ༠༣་རང་བྱུང་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.5412415864045578
  ocr_word_median_confidence_index: 0.5199999809265137
quality: null
bases:
  I1KG22341:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22341
      total_pages: 848
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22341.txt
    statistics:
      ocr_word_median_confidence_index: 0.5199999809265137
      ocr_word_mean_confidence_index: 0.5412415864045578
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
