id: P006668
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:14:47.757025
source_metadata:
  id: bdr:W1KG22301
  title: སྐྱེས་རབས་བརྒྱ་པ།
  author: ''
  volumes:
    11d7e0ad8b514dcf92316872f5d68711:
      image_group_id: I1KG22341
      title: ''
      volume_number: 1
      total_pages: 848
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
